{
 "title": "HTTP Requests",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "query": "ap-east-1,ap-northeast-1,ap-northeast-2,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-west-1,eu-west-2,eu-west-3,sa-east-1,us-east-1,us-west-1,us-west-2"
   },
   { "name": "refs" }
  ]
 },
 "panels": [
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Projects with Status Code (5m buckets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "SELECT\n  timestamp_minute,\n  COUNTIF(status_code_2xx > 0) AS status_code_2xx,\n  COUNTIF(status_code_3xx > 0) AS status_code_3xx,\n  COUNTIF(status_code_4xx > 0) AS status_code_4xx,\n  COUNTIF(status_code_5xx > 0) AS status_code_5xx\nFROM\n  `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized_5m`\n  JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND request_type = 'auth'\n  AND base_region IN ($region)\n  AND (\n    '$refs' = ''\n    OR '$refs' LIKE '%' || ref || '%'\n  )\nGROUP BY\n  timestamp_minute\norder by\n  timestamp_minute"
    }
   ]
  },
  {
   "title": "HTTP Requests (5m buckets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "SELECT\n  timestamp_minute,\n  SUM(status_code_2xx) AS status_code_2xx,\n  SUM(status_code_3xx) AS status_code_3xx,\n  SUM(status_code_4xx) AS status_code_4xx,\n  SUM(status_code_5xx) AS status_code_5xx\nFROM\n  `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized_5m`\n  JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND request_type = 'auth'\n  AND base_region IN ($region)\n  AND (\n    '$refs' = ''\n    OR '$refs' LIKE '%' || ref || '%'\n  )\nGROUP BY\n  timestamp_minute\nORDER BY\n  timestamp_minute"
    }
   ]
  },
  {
   "title": "Projects with Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "WITH\n  minutes AS (\n    SELECT\n      TIMESTAMP_SECONDS(UNIX_SECONDS('2024-07-01') + sequence * 60) AS timestamp_minute\n    FROM\n      UNNEST (\n        GENERATE_ARRAY(\n          1,\n          TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), '2024-07-01', MINUTE)\n        )\n      ) AS sequence\n  ),\n  distinct_project_counts AS (\n    SELECT\n      timestamp_minute,\n      COUNTIF(status_code_2xx > 0) AS status_code_2xx,\n      COUNTIF(status_code_3xx > 0) AS status_code_3xx,\n      COUNTIF(status_code_4xx > 0) AS status_code_4xx,\n      COUNTIF(status_code_5xx > 0) AS status_code_5xx\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n      JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\n    WHERE\n      $__timeFilter(timestamp_minute)\n      AND request_type = 'auth'\n      AND base_region IN ($region)\n      AND (\n        '$refs' = ''\n        OR '$refs' LIKE '%' || ref || '%'\n      )\n    GROUP BY\n      timestamp_minute\n  )\nSELECT\n  timestamp_minute,\n  COALESCE(status_code_2xx, 0) AS status_code_2xx,\n  COALESCE(status_code_3xx, 0) AS status_code_3xx,\n  COALESCE(status_code_4xx, 0) AS status_code_4xx,\n  COALESCE(status_code_5xx, 0) AS status_code_5xx\nFROM\n  minutes\n  LEFT JOIN distinct_project_counts USING (timestamp_minute)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND timestamp_minute <= (\n    SELECT\n      MAX(timestamp_minute)\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n    WHERE\n      timestamp_minute > TIMESTAMP_ADD(CURRENT_TIMESTAMP, INTERVAL -10 MINUTE)\n  )\nORDER BY\n  timestamp_minute"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "WITH\n  minutes AS (\n    SELECT\n      TIMESTAMP_SECONDS(UNIX_SECONDS('2024-07-01') + sequence * 60) AS timestamp_minute\n    FROM\n      UNNEST (\n        GENERATE_ARRAY(\n          1,\n          TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), '2024-07-01', MINUTE)\n        )\n      ) AS sequence\n  ),\n  region_requests AS (\n    SELECT\n      timestamp_minute,\n      SUM(status_code_2xx) AS status_code_2xx,\n      SUM(status_code_3xx) AS status_code_3xx,\n      SUM(status_code_4xx) AS status_code_4xx,\n      SUM(status_code_5xx) AS status_code_5xx\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n      JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\n    WHERE\n      $__timeFilter(timestamp_minute)\n      AND request_type = 'auth'\n      AND base_region IN ($region)\n      AND (\n        '$refs' = ''\n        OR '$refs' LIKE '%' || ref || '%'\n      )\n    GROUP BY\n      timestamp_minute\n  )\nSELECT\n  timestamp_minute,\n  COALESCE(status_code_2xx, 0) AS status_code_2xx,\n  COALESCE(status_code_3xx, 0) AS status_code_3xx,\n  COALESCE(status_code_4xx, 0) AS status_code_4xx,\n  COALESCE(status_code_5xx, 0) AS status_code_5xx\nFROM\n  minutes\n  LEFT JOIN region_requests USING (timestamp_minute)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND timestamp_minute <= (\n    SELECT\n      MAX(timestamp_minute)\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n    WHERE\n      timestamp_minute > TIMESTAMP_ADD(CURRENT_TIMESTAMP, INTERVAL -10 MINUTE)\n  )\nORDER BY\n  timestamp_minute"
    }
   ]
  },
  { "title": "PostgREST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Projects with Status Code (5m buckets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "SELECT\n  timestamp_minute,\n  COUNTIF(status_code_2xx > 0) AS status_code_2xx,\n  COUNTIF(status_code_3xx > 0) AS status_code_3xx,\n  COUNTIF(status_code_4xx > 0) AS status_code_4xx,\n  COUNTIF(status_code_5xx > 0) AS status_code_5xx\nFROM\n  `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized_5m`\n  JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND request_type = 'rest'\n  AND base_region IN ($region)\n  AND (\n    '$refs' = ''\n    OR '$refs' LIKE '%' || ref || '%'\n  )\nGROUP BY\n  timestamp_minute\norder by\n  timestamp_minute"
    }
   ]
  },
  {
   "title": "HTTP Requests (5m buckets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "SELECT\n  timestamp_minute,\n  SUM(status_code_2xx) AS status_code_2xx,\n  SUM(status_code_3xx) AS status_code_3xx,\n  SUM(status_code_4xx) AS status_code_4xx,\n  SUM(status_code_5xx) AS status_code_5xx\nFROM\n  `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized_5m`\n  JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND request_type = 'rest'\n  AND base_region IN ($region)\n  AND (\n    '$refs' = ''\n    OR '$refs' LIKE '%' || ref || '%'\n  )\nGROUP BY\n  timestamp_minute\nORDER BY\n  timestamp_minute"
    }
   ]
  },
  {
   "title": "Projects with Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "WITH\n  minutes AS (\n    SELECT\n      TIMESTAMP_SECONDS(UNIX_SECONDS('2024-07-01') + sequence * 60) AS timestamp_minute\n    FROM\n      UNNEST (\n        GENERATE_ARRAY(\n          1,\n          TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), '2024-07-01', MINUTE)\n        )\n      ) AS sequence\n  ),\n  distinct_project_counts AS (\n    SELECT\n      timestamp_minute,\n      COUNTIF(status_code_2xx > 0) AS status_code_2xx,\n      COUNTIF(status_code_3xx > 0) AS status_code_3xx,\n      COUNTIF(status_code_4xx > 0) AS status_code_4xx,\n      COUNTIF(status_code_5xx > 0) AS status_code_5xx\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n      JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\n    WHERE\n      $__timeFilter(timestamp_minute)\n      AND request_type = 'rest'\n      AND base_region IN ($region)\n      AND (\n        '$refs' = ''\n        OR '$refs' LIKE '%' || ref || '%'\n      )\n    GROUP BY\n      timestamp_minute\n  )\nSELECT\n  timestamp_minute,\n  COALESCE(status_code_2xx, 0) AS status_code_2xx,\n  COALESCE(status_code_3xx, 0) AS status_code_3xx,\n  COALESCE(status_code_4xx, 0) AS status_code_4xx,\n  COALESCE(status_code_5xx, 0) AS status_code_5xx\nFROM\n  minutes\n  LEFT JOIN distinct_project_counts USING (timestamp_minute)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND timestamp_minute <= (\n    SELECT\n      MAX(timestamp_minute)\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n    WHERE\n      timestamp_minute > TIMESTAMP_ADD(CURRENT_TIMESTAMP, INTERVAL -10 MINUTE)\n  )\nORDER BY\n  timestamp_minute"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "dataset": "raw_infra",
     "location": "EU",
     "project": "supabase-etl-prod-eu",
     "rawSql": "WITH\n  minutes AS (\n    SELECT\n      TIMESTAMP_SECONDS(UNIX_SECONDS('2024-07-01') + sequence * 60) AS timestamp_minute\n    FROM\n      UNNEST (\n        GENERATE_ARRAY(\n          1,\n          TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), '2024-07-01', MINUTE)\n        )\n      ) AS sequence\n  ),\n  region_requests AS (\n    SELECT\n      timestamp_minute,\n      SUM(status_code_2xx) AS status_code_2xx,\n      SUM(status_code_3xx) AS status_code_3xx,\n      SUM(status_code_4xx) AS status_code_4xx,\n      SUM(status_code_5xx) AS status_code_5xx\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n      JOIN `supabase-etl-prod-eu.dbt.supabase_projects` USING (ref)\n    WHERE\n      $__timeFilter(timestamp_minute)\n      AND request_type = 'rest'\n      AND base_region IN ($region)\n      AND (\n        '$refs' = ''\n        OR '$refs' LIKE '%' || ref || '%'\n      )\n    GROUP BY\n      timestamp_minute\n  )\nSELECT\n  timestamp_minute,\n  COALESCE(status_code_2xx, 0) AS status_code_2xx,\n  COALESCE(status_code_3xx, 0) AS status_code_3xx,\n  COALESCE(status_code_4xx, 0) AS status_code_4xx,\n  COALESCE(status_code_5xx, 0) AS status_code_5xx\nFROM\n  minutes\n  LEFT JOIN region_requests USING (timestamp_minute)\nWHERE\n  $__timeFilter(timestamp_minute)\n  AND timestamp_minute <= (\n    SELECT\n      MAX(timestamp_minute)\n    FROM\n      `supabase-etl-prod-eu.raw_infra.cloudflare_logs_status_code_groups_materialized`\n    WHERE\n      timestamp_minute > TIMESTAMP_ADD(CURRENT_TIMESTAMP, INTERVAL -10 MINUTE)\n  )\nORDER BY\n  timestamp_minute"
    }
   ]
  }
 ]
}