{
 "title": "Storage API Dashboard",
 "description": "Monitor metrics for node.js and express router status.",
 "tags": [
  "node.js",
  "express",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(storage_api_nodejs_version_info, instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(storage_api_http_request_duration_seconds_bucket, le)"
    }
   },
   {
    "name": "tolerated",
    "query": {
     "query": "label_values(storage_api_http_request_duration_seconds_bucket, le)"
    }
   },
   { "name": "restarts_interval", "query": "1d,7d,14d,30d" },
   {
    "name": "tenant_id",
    "query": {
     "query": "label_values(storage_api_http_request_duration_seconds_bucket, tenant_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview & Targets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apdex Score: target $target s, tolerated $tolerated s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n        (   \n                sum(storage_api_http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",status_code=~\"^2..$\"})\n                + (\n                        sum(storage_api_http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$tolerated\",status_code=~\"^2..$\"})\n                        - sum(storage_api_http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",status_code=~\"^2..$\"})\n                ) / 2\n        ) / sum(storage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^2..$\"})\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(storage_api_http_request_duration_seconds_count{instance=~\"$instance\",tenant_id=~\"$tenant_id\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(storage_api_http_request_duration_seconds_count{instance=~\"$instance\", tenant_id=~\"$tenant_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storage_api_http_response_size_bytes_sum{instance=~\"$instance\"}) + sum(storage_api_http_request_size_bytes_sum{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "storage_api_http" }
   ]
  },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(storage_api_process_start_time_seconds{instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(rate(storage_api_process_cpu_seconds_total{instance=~\"$instance\"}[$__range]))[$__range]"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(storage_api_process_resident_memory_bytes{instance=~\"$instance\"} / (2*1024*1024*1024))[$__range]"
    }
   ]
  },
  {
   "title": "Pg Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_num_backends{Name=~\"staging-db-$tenant_id\"}[$__interval]",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Responses By Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(\n\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[4]..$\",tenant_id=~\"$tenant_id\"}[$__range] OR on() vector(0)\n))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(increase(\n\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[5]..$\",tenant_id=~\"$tenant_id\"}[$__range] OR on() vector(0)\n))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(increase(\n\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[2]..$\",tenant_id=~\"$tenant_id\"}[$__range] OR on() vector(0)\n))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(increase(\n\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[2]..$\",tenant_id=~\"$tenant_id\"}[$__range] OR on() vector(0)\n)) +\nsum(increase(\n\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[4]..$\",tenant_id=~\"$tenant_id\"}[$__range] OR on() vector(0)\n)) +\nsum(increase(\n\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[5]..$\",tenant_id=~\"$tenant_id\"}[$__range] OR on() vector(0)\n))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "400 Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "(\n\trate(sum(\n\t\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[4]..$\",tenant_id=~\"$tenant_id\"} OR on() vector(0)\n\t)) / \n\tsum(\n\t\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",tenant_id=~\"$tenant_id\"}\n\t)\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "500 Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "(\n\tsum(\n\t\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",status_code=~\"^[5]..$\",tenant_id=~\"$tenant_id\"} OR on() vector(0)\n\t) / \n\tsum(\n\t\tstorage_api_http_request_duration_seconds_count{instance=~\"$instance\",tenant_id=~\"$tenant_id\"}\n\t)\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Requests By Tenants",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(sum(increase(storage_api_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\", status_code=~\"^[2]..$\"}[$__range])) by (tenant_id, status_code))",
     "legendFormat": "tenant_id={{ tenant_id }}"
    },
    {
     "expr": "(sum(increase(storage_api_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\", status_code=~\"^[4]..$\"}[$__range])) by (tenant_id, status_code))",
     "legendFormat": "tenant_id={{ tenant_id }}"
    },
    {
     "expr": "(sum(increase(storage_api_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\", status_code=~\"^[5]..$\"}[$__range])) by (tenant_id, status_code))",
     "legendFormat": "tenant_id={{ tenant_id }}"
    }
   ]
  },
  {
   "title": "Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "increase(sum(storage_api_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\", status_code=~\"^[45]..$\"}[$__interval]) by (status_code, tenant_id))",
     "legendFormat": "{{ tenant_id }} - {{ status_code }}"
    }
   ]
  },
  { "title": "Uploads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "File Uploads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(increase(storage_api_upload_started{tenant_id=~\"$tenant_id\"}[$__range]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(increase(storage_api_upload_success{tenant_id=~\"$tenant_id\"}[$__range]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(increase(storage_api_upload_success{tenant_id=~\"$tenant_id\", is_multipart=\"true\"}[$__range]))",
     "legendFormat": "Multi Part"
    },
    {
     "expr": "sum(increase(storage_api_upload_success{tenant_id=~\"$tenant_id\", is_multipart=\"false\"}[$__range]))",
     "legendFormat": "Standard"
    }
   ]
  },
  {
   "title": "S3 Upload Part AVG Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(storage_api_s3_upload_part_bucket{tenant_id=~\"$tenant_id\"}[$__interval]) by (le, tenant_id))",
     "legendFormat": "{{ tenant_id }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests VS PgBouncer clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(storage_api_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\"}[$__interval])) by (tenant_id)",
     "legendFormat": "Request Count - {{ tenant_id }}"
    },
    {
     "expr": "pgbouncer_used_clients{Name=~\"prod-db-$tenant_id\"}[$__interval]",
     "legendFormat": "PgBouncer Connections - {{ Name }}"
    },
    {
     "expr": "pg_stat_database_num_backends{Name=~\"prod-db-$tenant_id\"}[$__interval]",
     "legendFormat": "Pg Native connections - {{ Name }}"
    }
   ]
  },
  {
   "title": "Total Number of Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(storage_api_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\"}[$__interval]))",
     "legendFormat": "{{ tenant_id }} - {{route}} - {{method}} "
    }
   ]
  },
  {
   "title": "Http Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(storage_api_http_request_duration_seconds_bucket{tenant_id=~\"$tenant_id\"}[$__interval]) by (le, route, method, status_code))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(storage_api_http_request_duration_seconds_bucket{tenant_id=~\"$tenant_id\"}[$__interval])) by (le, route, method, tenant_id))",
     "legendFormat": "{{ tenant_id }} - {{route}} - {{method}} "
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Queue Pending Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(storage_api_queue_job_scheduled{tenant_id=~\"$tenant_id\"}[$__range]) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Failed and Retried",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(storage_api_queue_job_retry_failed{tenant_id=~\"$tenant_id\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Job Failed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(storage_api_queue_job_error{tenant_id=~\"$tenant_id\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Completed Per Tenant",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(storage_api_queue_job_completed{name=~\"[a-z].*\"}[$__interval]) by (tenant_id))",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Queue Completed Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(storage_api_queue_job_completed{tenant_id=~\"$tenant_id\"}[$__range]) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Scheduling Time AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(storage_api_queue_job_scheduled_time_sum{tenant_id=~\"$tenant_id\"}[$__interval]) / rate(storage_api_queue_job_scheduled_time_count{tenant_id=~\"$tenant_id\"}[$__interval])) by (le, name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Messages Scheduled Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(storage_api_queue_job_scheduled_time_count[$__range])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "DB Query Performance (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(storage_api_database_query_performance_bucket{tenant_id=~\"$tenant_id\"}[$__interval])) by (le, name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Database Performance AVG",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(storage_api_database_query_performance_sum{tenant_id=~\"$tenant_id\"}[$__interval]) / rate(storage_api_database_query_performance_count{tenant_id=~\"$tenant_id\"}[$__interval])) by (le, name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "DB Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(storage_api_database_query_performance_count{tenant_id=~\"$tenant_id\"}[$__interval])) by (name)",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Pg Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "pg_stat_database_num_backends{Name=~\"prod-db-$tenant_id\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "pgbouncer_used_clients{Name=~\"prod-db-$tenant_id\"}[1m]"
    }
   ]
  },
  { "title": "Node.js Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Eventloop Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "storage_api_nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "last"
    },
    {
     "expr": "storage_api_nodejs_eventloop_lag_p99_seconds{instance=~\"$instance\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "storage_api_nodejs_eventloop_lag_p50_seconds{instance=~\"$instance\"}",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Rate of CPU Time Spent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(storage_api_process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Process Memory %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "storage_api_process_resident_memory_bytes{instance=~\"$instance\"} / (2*1024*1024*1024)",
     "legendFormat": "resident memory {{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "storage_api_process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "virtual memory {{instance}}"
    },
    {
     "expr": "storage_api_process_heap_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap memory {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "storage_api_process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident memory {{instance}}"
    },
    {
     "expr": "storage_api_process_heap_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap memory {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Open FDs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_api_process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( storage_api_process_open_fds{instance=~\"$instance\"} / storage_api_process_max_fds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_api_nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "storage_api_nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  { "title": "Node.js Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Rate of Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(storage_api_nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(storage_api_nodejs_gc_duration_seconds_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "storage_api_nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "storage_api_nodejs_gc_duration_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "storage_api_nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "storage_api_nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{space}}"
    }
   ]
  }
 ]
}