name: Build and Deploy to Prod

on:
  workflow_dispatch:

jobs:
  prod-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: build & deploy to prod targets
        run: |
          ./scripts/deploy.sh prod scripts/prod-regions.txt
          ./scripts/deploy-salt.sh prod scripts/prod-regions.txt
          ./scripts/vmagent-deploy.sh prod scripts/prod-regions.txt
        env:
          GRAFANA_UPLOADER_CF_ID: ${{ secrets.GRAFANA_UPLOADER_CF_ID }}
          GRAFANA_UPLOADER_CF_SECRET: ${{ secrets.GRAFANA_UPLOADER_CF_SECRET }}
